# The compiler
FC = gfortran

FCFLAGS2 = -g -fbacktrace -fbounds-check 
FCFLAGS = -O2 
OBFLAGS = -c


relative_plot_param: relative_plot_param.f90
	$(FC) -o relative_plot_param $(FCFLAGS) relative_plot_param.f90


